"""initial

Revision ID: 202147c4cb7e
Revises: 
Create Date: 2026-05-27 20:12:59.521886

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '202147c4cb7e'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alugueis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('carro_id', sa.Integer(), nullable=True),
    sa.Column('dias', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alugueis_id'), 'alugueis', ['id'], unique=False)
    op.create_table('carros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=False),
    sa.Column('placa', sa.String(), nullable=True),
    sa.Column('disponivel', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_index(op.f('ix_carros_id'), 'carros', ['id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_carros_id'), table_name='carros')
    op.drop_table('carros')
    op.drop_index(op.f('ix_alugueis_id'), table_name='alugueis')
    op.drop_table('alugueis')
    # ### end Alembic commands ###